API_ID: 21256594
API_HASH: 34b4ae3055e20c42951864422e552273
BOT_TOKEN: 6062079586:AAFkqVjWeqjTQa7bDcLZ0c44UJPQ9Bw8oSg


MONGO_URL: mongodb+srv://ccchk:ccchk@cluster0.ppp4xhj.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-13392.c91.us-east-1-3.ec2.cloud.redislabs.com
REDIS_PORT: 13392
REDIS_PASS: KfQ5QA3S4ft7W4XrLRkmghFYuy2UR6LB

SESSION_API_ID: 21256594
SESSION_API_HASH: 34b4ae3055e20c42951864422e552273
SESSION_STRING: 1AZWarzQBu4vmgdIuoZqyrSeoNq-rYdRzATpljOv1qQsy_cB3FkV2s0GopkHNsmQ_6R3ugHU5g_RwTcB3gYRZnMOyqXzJ2sA9UKQuRYlQyHHP-1jem8O9eJR9kAnRwgPHtBnuq54j3Lr9SxxjK-QGXqr7SEcMwqp03LRmu-ItTkWzzTugwtI0YEOUSttaa8qDG25y6ZPLNnIdpVLDSvDXSZo6UMLoNyGFmanu93vAu64kGEJOOkee-BTFlZuu1l4wqsmU2xpCWiD2CM1lkOKMAecc05mzF_41-hGxkL6a3e1jHDe89iROSLf7LYYKJwNksQuDMJFgom-242tma7fguT5vDLGDhEU=

ADMINS: 
  - 5721949879

OWNER: 5721949879

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: CHATTING_HUB_69
# LOG_CHAT: 
LOG_CHAT: -1001664991104



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

